// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jps",
                            IsActive = true,
                            Name = "Apple",
                            Price = 1000m,
                            Stock = 47
                        },
                        new
                        {
                            Id = 2,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jps",
                            IsActive = true,
                            Name = "Samsung",
                            Price = 900m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jps",
                            IsActive = true,
                            Name = "Nokia",
                            Price = 500m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "Telefon Açıklaması",
                            ImageUrl = "1.jps",
                            IsActive = true,
                            Name = "Huawei",
                            Price = 320m,
                            Stock = 120
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
